In [66]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sb
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error

In [2]:
train_df = pd.read_csv('training_data.csv')

train_df.head()

,url_id,timedelta,n_tokens_title,n_tokens_content,n_unique_tokens,n_non_stop_words,n_non_stop_unique_tokens,num_hrefs,num_self_hrefs,num_imgs,...,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,shares
0,1,731,12,219,0.663594,1.0,0.815385,4,2,1,...,0.100000,0.7,-0.350000,-0.600,-0.200000,0.500000,-0.187500,0.000000,0.187500,593
1,2,731,9,255,0.604743,1.0,0.791946,3,1,1,...,0.033333,0.7,-0.118750,-0.125,-0.100000,0.000000,0.000000,0.500000,0.000000,711
2,3,731,9,211,0.575130,1.0,0.663866,3,1,1,...,0.100000,1.0,-0.466667,-0.800,-0.133333,0.000000,0.000000,0.500000,0.000000,1500
3,5,731,13,1072,0.415646,1.0,0.540890,19,19,20,...,0.033333,1.0,-0.220192,-0.500,-0.050000,0.454545,0.136364,0.045455,0.136364,505
4,6,731,10,370,0.559889,1.0,0.698198,2,2,0,...,0.136364,0.6,-0.195000,-0.400,-0.100000,0.642857,0.214286,0.142857,0.214286,855

In [11]:
train_df.describe()

,url_id,timedelta,n_tokens_title,n_tokens_content,n_unique_tokens,n_non_stop_words,n_non_stop_unique_tokens,num_hrefs,num_self_hrefs,num_imgs,...,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,shares
count,28786.000000,28786.000000,28786.000000,28786.000000,28786.000000,28786.000000,28786.000000,28786.000000,28786.000000,28786.000000,...,28786.000000,28786.000000,28786.000000,28786.000000,28786.000000,28786.000000,28786.00000,28786.000000,28786.000000,28786.000000
mean,19878.678524,353.520635,10.403460,546.455082,0.555111,1.006600,0.695780,10.873063,3.301674,4.548496,...,0.095110,0.756500,-0.260026,-0.522700,-0.107939,0.282659,0.07220,0.341162,0.156628,3428.658549
std,11461.174637,214.420324,2.121334,470.409467,4.130828,6.138155,3.830214,11.155409,3.868232,8.342588,...,0.070577,0.247865,0.127850,0.290469,0.095253,0.323911,0.26614,0.189085,0.226958,12693.940388
min,1.000000,8.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,-1.000000,-1.000000,-1.000000,0.000000,-1.00000,0.000000,0.000000,1.000000
25%,9916.250000,163.000000,9.000000,245.000000,0.470735,1.000000,0.625926,4.000000,1.000000,1.000000,...,0.050000,0.600000,-0.329167,-0.700000,-0.125000,0.000000,0.00000,0.166667,0.000000,940.250000
50%,19922.500000,337.000000,10.000000,410.000000,0.539302,1.000000,0.691043,8.000000,3.000000,1.000000,...,0.100000,0.800000,-0.253756,-0.500000,-0.100000,0.150000,0.00000,0.500000,0.000000,1400.000000
75%,29852.750000,542.000000,12.000000,716.000000,0.608527,1.000000,0.755155,14.000000,4.000000,4.000000,...,0.100000,1.000000,-0.187500,-0.300000,-0.050000,0.500000,0.15000,0.500000,0.250000,2800.000000
max,39643.000000,731.000000,23.000000,8474.000000,701.000000,1042.000000,650.000000,162.000000,74.000000,128.000000,...,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.00000,0.500000,1.000000,843300.000000

In [30]:
x_train = train_df.iloc[:,1:]
x_train.head()

,timedelta,n_tokens_title,n_tokens_content,n_unique_tokens,n_non_stop_words,n_non_stop_unique_tokens,num_hrefs,num_self_hrefs,num_imgs,num_videos,...,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,shares
0,731,12,219,0.663594,1.0,0.815385,4,2,1,0,...,0.100000,0.7,-0.350000,-0.600,-0.200000,0.500000,-0.187500,0.000000,0.187500,593
1,731,9,255,0.604743,1.0,0.791946,3,1,1,0,...,0.033333,0.7,-0.118750,-0.125,-0.100000,0.000000,0.000000,0.500000,0.000000,711
2,731,9,211,0.575130,1.0,0.663866,3,1,1,0,...,0.100000,1.0,-0.466667,-0.800,-0.133333,0.000000,0.000000,0.500000,0.000000,1500
3,731,13,1072,0.415646,1.0,0.540890,19,19,20,0,...,0.033333,1.0,-0.220192,-0.500,-0.050000,0.454545,0.136364,0.045455,0.136364,505
4,731,10,370,0.559889,1.0,0.698198,2,2,0,0,...,0.136364,0.6,-0.195000,-0.400,-0.100000,0.642857,0.214286,0.142857,0.214286,855

In [35]:
y_train = train_df.iloc[:,-1]
y_train

0          593
1          711
2         1500
3          505
4          855
5          556
6          891
7         3600
8          710
9         1900
10         823
11       10000
12        1600
13       13600
14        3100
15        5700
16        2800
17         598
18         445
19        1500
20         852
21        1500
22        1800
23         462
24         425
25        3900
26         480
27        3600
28         343
29        2600
         ...
28756     4600
28757     1400
28758     2600
28759     2500
28760     1300
28761     1500
28762     4600
28763     1600
28764     1400
28765     5700
28766     2100
28767     1400
28768     2400
28769    24300
28770      947
28771     3200
28772     1400
28773     1100
28774     1200
28775     1000
28776     2400
28777     1500
28778      914
28779     1700
28780     1000
28781     1400
28782     1200
28783     1900
28784     1900
28785     1100
Name:  shares, Length: 28786, dtype: int64

In [36]:
x_train.shape,y_train.shape

((28786, 60), (28786,))

In [37]:
X_train,X_test,y_train,y_test = train_test_split(x_train,y_train,test_size=0.33,random_state=42)

X_train.shape,y_train.shape,X_test.shape,y_test.shape

((19286, 60), (19286,), (9500, 60), (9500,))

In [63]:
## Mean Absolute Percentage Error (MAPE)
from sklearn.utils import check_array

def mean_absolute_percentage_error(y_pred,y_true):
    #y_pred = np.transpose(y_pred)
    #y_true = np.transpose(y_true)
    #y_true, y_pred = check_array(y_true,y_pred)
    
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

In [64]:
y_train = np.array(y_train).reshape(-1,1)
y_test = np.array(y_test).reshape(-1,1)
y_train.shape,y_test.shape

((19286, 1), (9500, 1))

In [65]:
# Random Forest

regr = RandomForestRegressor(max_depth=2, random_state=0,n_estimators=100)
regr.fit(X_train,y_train)
prediction_train = np.array(regr.predict(X_train)).reshape(-1,1)
prediction_test = np.array(regr.predict(X_test)).reshape(-1,1)
print("Training accuracy: ",mean_absolute_percentage_error(prediction_train,y_train))
print("Test accuracy: ",mean_absolute_percentage_error(prediction_test,y_test))

C:\Users\ABC\Miniconda3\envs\fastai\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.

Training accuracy:  150.76511551906418
Test accuracy:  144.87643578394193

In [69]:
## Mean square error
prediction_train = np.array(regr.predict(X_train)).reshape(1,-1)
prediction_test = np.array(regr.predict(X_test)).reshape(1,-1)

y_train = np.array(y_train).reshape(1,-1)
y_test = np.array(y_test).reshape(1,-1)

print("Training accuracy: ",mean_squared_error(prediction_train,y_train))
print("Test accuracy: ",mean_squared_error(prediction_test,y_test))

Training accuracy:  19503133.317602485
Test accuracy:  32894031.027429573